cookie:
  secret: 'REPLACE SECRET IN DEVELOPMENT.YAML'
session:
  secret: 'REPLACE SECRET IN DEVELOPMENT.YAML'
base:
    path: ''
run:
  host: 'localhost'
  port: 3000
  path: '/run'
nez:
    path: './nez/nez.jar'
    option: 'parse'
    env: ''
    
generate:
    path: '../nez/nez.jar'
    option: 'nez.bx.CGenerate'
    env: ''
format:
    path: '../nez/nez.jar'
    option: 'nez.bx.CFormat'
    env: ''
check:
    path: '../nez/nez.jar'
    option: 'nez.bx.CCheck'
    env: ''
